project:
  type: website
  output-dir: docs

website:
  title: "redecweb"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: People

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



