project:
  type: website
  output-dir: docs

website:
  title: "Red Ibérica de Seguimiento del Decaimiento Forestal"
  repo-url: "https://github.com/red-decaimiento/web"
  favicon: images/logo_redec.png
  page-navigation: false
  search: true
  page-footer: 
    background: "#F6F5F3"
    center: © 2024  &middot; Made with {{< fa brands r-project >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) 
    right:
      - icon: github
        href: https://github.com/red-decaimiento/web
        
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: people/index.qmd
        text: People
      
format:
  html:
    theme: 
      - styles/custom.scss
      - cosmo
    toc: true


